modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/manel740/StutterFix-Reforged/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/stutterfix-reforged"

[[mods]]
modId="stutterfix"
version="${version}"
displayName="StutterFix Reforged"
description='''
StutterFix optimizes Minecraft's thread management to reduce stuttering and improve performance.
This mod adjusts the number of worker threads and their priorities to minimize frame drops during chunk generation and world loading.
'''
authors="Manel740"
logoFile="assets/stutterfix/icon.png"

[[dependencies.stutterfix]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.stutterfix]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"